CREATE DATABASE IF NOT EXISTS springtext DEFAULT CHARACTER SET utf8mb4;
USE springtext;

CREATE TABLE IF NOT EXISTS user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE
);
